package main

import "strings"

/*
Wrap HTML fragment generated by tohtml.ToHTML() if more HTML
to make it fully stand-alone page
*/

var (
	css = `
	body {
		margin: 0px 16px 0px 16px;
		background: white;
		color: #333;
		/* same as github.com */
		font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial,
		  sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
		font-size: 12pt;
		line-height: 1.4;
	  }

	  code {
		background-color: #f9f9f9;
	  }

	  div.title {
		font-size: 200%;
	  }

	  div > p,
	  li > p {
		line-height: 1.5em;
	  }

	  .todo-checked {
		background: lightblue;
	  }

	  .lvl1 {
		margin-left: 16px;
	  }

	  .lvl2 {
		margin-left: 32px;
	  }

	  .lvl3 {
		margin-left: 48px;
	  }

	  .lvl4 {
		margin-left: 64px;
	  }

	  .lvl5 {
		margin-left: 80px;
	  }

	  .lvl6 {
		margin-left: 96px;
	  }

	  h1,
	  h2,
	  h3 {
		font-size: medium;
	  }

	  h1 {
		margin-bottom: 2px;
		padding: 0;
	  }

	  img {
		border: 0;
	  }

	  blockquote {
		font-style: italic;
	  }

	  div#tophdr {
		font-size: 10pt;
		font-weight: bold;
		margin: 0px;
		padding: 6pt;
		padding-left: 16px;
		padding-right: 16px;
	  }

	  div.centered {
		text-align: center;
	  }

	  div.centered table {
		margin: 0 auto;
		text-align: left;
	  }

	  div#post {
		min-width: 400px;
		max-width: 960px;
	  }

	  hr {
		border: 0;
		border-top: 1px solid #eee;
	  }

	  .title,
	  .title:visited {
		color: #000;
		font-weight: bold;
		text-decoration: none;
		font-size: 140%;
	  }

	  a {
		color: #0894f1;
		text-decoration: none;
		background: transparent;
	  }

	  a:hover {
		text-decoration: underline;
	  }

	  .taglink {
		color: gray;
		text-decoration: none;
	  }

	  a.taglink:hover {
		text-decoration: underline;
	  }

	  .onHoverVisible a {
		color: white;
	  }

	  .onHoverVisible a:hover {
		color: gray;
	  }

	  .article-header {
		margin-top: 16px;
	  }

	  .hdr-image:hover {
		filter: grayscale(100%);
	  }

	  /* https://stackoverflow.com/questions/19390690/css-media-queries-to-hide-and-show-page-elements
	  TODO: it still loads the image if it's inside div hidden with this trick, at least in Chrome's device simulator
	  See: https://timkadlec.com/2012/04/media-query-asset-downloading-results/
	  */
	  @media only screen and (max-width: 767px),
		only screen and (max-device-width: 767px) {
		.hide-mobile {
		  display: none;
		}
	  }

	  .article-meta {
		display: flex;
		color: gray;
		font-size: 80%;
	  }

	  .ad {
		font-family: geneva, helvetica, arial, sans-serif;
		font-size: 12pt;
		background-color: #fbf0fa;
		padding: 4px 8px;
	  }

	  .adl {
		color: green;
	  }

	  .light {
		color: #999999;
	  }

	  .invisible {
		color: #fcfcfa;
	  }

	  .visible {
		color: #000;
	  }

	  .nowrap {
		white-space: nowrap;
	  }

	  .inactiveSearch {
		color: gray;
		font-style: italic;
	  }

	  .activeSearch {
		color: black;
		font-style: normal;
	  }

	  /* drop-down menu based on http://csswizardry.com/2011/02/creating-a-pure-css-dropdown-menu/ */

	  #nav {
		list-style: none;
		font-weight: bold;
		float: right;
		margin-top: 0px;
		position: relative;
		z-index: 5;
	  }

	  #nav li {
		float: left;
		margin-right: 4pt;
		position: relative;
	  }

	  #nav a {
		display: block;
		color: #aaa;
		text-decoration: none;
		border-bottom: 1px solid transparent;
	  }

	  #nav a:hover {
		color: #666;
		text-decoration: none;
		border-bottom: 1px solid #666;
	  }

	  /* drop-down */

	  #nav ul {
		background: #4d5456;
		list-style: none;
		position: absolute;
		left: -9999px;
	  }

	  #nav ul li {
		padding-top: 1px;
		float: none;
	  }

	  #nav ul a {
		white-space: nowrap;
	  }

	  #nav li:hover ul {
		padding: 8pt;
		left: -8pt;
	  }

	  #nav li:hover a {
		text-decoration: none;
	  }

	  #nav li:hover ul a {
		color: white;
		border-bottom: 3px solid transparent;
		text-decoration: none;
	  }

	  #nav li:hover ul li a:hover {
		border-bottom: 3px solid;
	  }

	  #container {
		margin-left: 16pt;
		margin-right: 16pt;
	  }

	  /* used in mainpage.html */

	  .mainpage-wrap {
		display: flex;
		flex-direction: column;
		align-items: center;
		color: #777;
		padding-right: 8px;
		padding-left: 8px;
	  }

	  .underline {
		border-bottom: 1px solid rgba(0, 0, 0, 0.1);
		padding-bottom: 4px;
		margin-bottom: 24px;
	  }

	  .articles-list-wrap {
		display: flex;
		flex-direction: column;
		align-items: center;
		line-height: 1.8;
	  }

	  .headline {
		line-height: 1.4em;
	  }

	  .headline a {
		color: #aaa;
		text-decoration: none;
		border-bottom: 1px solid transparent;
	  }

	  .headline a:hover {
		color: #666;
		text-decoration: none;
		border-bottom: 1px solid #666;
	  }

	  .notes-note-body {
		display: block;
		padding: 0px;
		margin: 0px;
		font-size: 12pt;
		white-space: pre-wrap;
	  }

	  .notes-tag-list {
		font-size: 8pt;
		margin-top: -12px;
		margin-bottom: 8px;
		opacity: 0.6;
	  }

	  .notes-tag:after {
		content: " \00b7 "; /* middot */
	  }

	  .notes-tag:last-child:after {
		content: "";
	  }

	  .notes-tag-count {
		color: #080;
	  }

	  .notes-tag-list a {
		padding: 0px;
		color: #080;
		text-decoration: none;
	  }

	  .notes-tag-list a:hover {
		text-decoration: underline;
	  }

	  .notes-meta {
		font-size: 8pt;
		display: inline-block;
		color: white;
		color: #080;
	  }

	  .notes-meta a {
		padding: 0px;
		color: #080;
		text-decoration: none;
	  }

	  .notes-meta a:hover {
		text-decoration: underline;
	  }

	  .notes-tags a {
		margin-left: 8px;
	  }

	  .notes-day {
		font-weight: bold;
		font-size: 8pt;
		padding: 0px;
		padding-right: 1em;
	  }

	  .note-code {
		background-color: #fdfdfd;
		border: 1px solid #e5e5e5;
		overflow-x: visible;
		padding: 0.5em;
		tab-size: 4;
	  }

	  .nav-prev-next {
		display: flex;
		justify-content: space-between;
		margin-bottom: 2em;
	  }

	  /*

	  Orginal Style from ethanschoonover.com/solarized (c) Jeremy Hull <sourdrums@gmail.com>

	  */

	  .hljs {
		display: block;
		overflow-x: auto;
		padding: 0.5em;
		background-color: #fdfdfd;
		color: #657b83;
		border: 1px solid #e5e5e5;
		overflow-x: visible;
		font-size: 85%;
		tab-size: 2;
	  }

	  .hljs-comment,
	  .hljs-quote {
		color: #93a1a1;
	  }

	  /* Solarized Green */

	  .hljs-keyword,
	  .hljs-selector-tag,
	  .hljs-addition {
		color: #859900;
	  }

	  /* Solarized Cyan */

	  .hljs-number,
	  .hljs-string,
	  .hljs-meta .hljs-meta-string,
	  .hljs-literal,
	  .hljs-doctag,
	  .hljs-regexp {
		color: #2aa198;
	  }

	  /* Solarized Blue */

	  .hljs-title,
	  .hljs-section,
	  .hljs-name,
	  .hljs-selector-id,
	  .hljs-selector-class {
		color: #268bd2;
	  }

	  /* Solarized Yellow */

	  .hljs-attribute,
	  .hljs-attr,
	  .hljs-variable,
	  .hljs-template-variable,
	  .hljs-class .hljs-title,
	  .hljs-type {
		color: #b58900;
	  }

	  /* Solarized Orange */

	  .hljs-symbol,
	  .hljs-bullet,
	  .hljs-subst,
	  .hljs-meta,
	  .hljs-meta .hljs-keyword,
	  .hljs-selector-attr,
	  .hljs-selector-pseudo,
	  .hljs-link {
		color: #cb4b16;
	  }

	  /* Solarized Red */

	  .hljs-built_in,
	  .hljs-deletion {
		color: #dc322f;
	  }

	  .hljs-formula {
		background: #eee8d5;
	  }

	  .hljs-emphasis {
		font-style: italic;
	  }

	  .hljs-strong {
		font-weight: bold;
	  }

	  /*
	  https://raw.githubusercontent.com/google/code-prettify/master/src/prettify.css
	  */

	  /**
	   * @license
	   * Copyright (C) 2015 Google Inc.
	   *
	   * Licensed under the Apache License, Version 2.0 (the "License");
	   * you may not use this file except in compliance with the License.
	   * You may obtain a copy of the License at
	   *
	   *      http://www.apache.org/licenses/LICENSE-2.0
	   *
	   * Unless required by applicable law or agreed to in writing, software
	   * distributed under the License is distributed on an "AS IS" BASIS,
	   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	   * See the License for the specific language governing permissions and
	   * limitations under the License.
	   */

	  /* Pretty printing styles. Used with prettify.js. */

	  /* SPAN elements with the classes below are added by prettyprint. */

	  .pln {
		color: #000;
	  }

	  /* plain text */

	  @media screen {
		.str {
		  color: #080;
		}
		/* string content */
		.kwd {
		  color: #008;
		}
		/* a keyword */
		.com {
		  color: #800;
		}
		/* a comment */
		.typ {
		  color: #606;
		}
		/* a type name */
		.lit {
		  color: #066;
		}
		/* a literal value */
		/* punctuation, lisp open bracket, lisp close bracket */
		.pun,
		.opn,
		.clo {
		  color: #660;
		}
		.tag {
		  color: #008;
		}
		/* a markup tag name */
		.atn {
		  color: #606;
		}
		/* a markup attribute name */
		.atv {
		  color: #080;
		}
		/* a markup attribute value */
		.dec,
		.var {
		  color: #606;
		}
		/* a declaration; a variable name */
		.fun {
		  color: red;
		}
		/* a function name */
	  }

	  /* Use higher contrast and text-weight for printable form. */

	  @media print, projection {
		.str {
		  color: #060;
		}
		.kwd {
		  color: #006;
		  font-weight: bold;
		}
		.com {
		  color: #600;
		  font-style: italic;
		}
		.typ {
		  color: #404;
		  font-weight: bold;
		}
		.lit {
		  color: #044;
		}
		.pun,
		.opn,
		.clo {
		  color: #440;
		}
		.tag {
		  color: #006;
		  font-weight: bold;
		}
		.atn {
		  color: #404;
		}
		.atv {
		  color: #060;
		}
	  }

	  /* Put a border around prettyprinted code snippets. */

	  pre.prettyprint {
		padding: 2px;
		border: 1px solid #888;
	  }

	  /* Specify class=linenums on a pre to get line numbering */

	  ol.linenums {
		margin-top: 0;
		margin-bottom: 0;
	  }

	  /* IE indents via margin-left */

	  li.L0,
	  li.L1,
	  li.L2,
	  li.L3,
	  li.L5,
	  li.L6,
	  li.L7,
	  li.L8 {
		list-style-type: none;
	  }

	  /* Alternate shading for lines */

	  li.L1,
	  li.L3,
	  li.L5,
	  li.L7,
	  li.L9 {
		background: #eee;
	  }

	  .share-me {
		font-size: 90%;
		color: gray;
		background-color: #f3fafd;
		display: inline-block;
		padding: 8px 16px;
	  }
	  .draft {
		color: red;
		font-size: 80%;
	  }

	  .github-link {
		font-size: 0.8em;
		position: fixed;
		right: 4px;
		top: 50px;
		padding: 4px 8px;
		border: 1px solid #666;
	  }

	  .github-link:hover {
		background-color: #f1f1f1;
	  }

	  pre.chroma {
		display: block;
		overflow-x: auto;
		padding: 0.5em;
		background-color: #fdfdfd;
		color: #657b83;
		border: 1px solid #e5e5e5;
		overflow-x: visible;
		font-size: 85%;
		tab-size: 2;
	  }

	  /* Background */
	  .chroma {
		color: #272822;
		background-color: #fafafa;
	  }
	  /* Error */
	  .chroma .err {
		color: #960050;
		background-color: #1e0010;
	  }
	  /* LineTableTD */
	  .chroma .lntd {
		vertical-align: top;
		padding: 0;
		margin: 0;
		border: 0;
	  }
	  /* LineTable */
	  .chroma .lntable {
		border-spacing: 0;
		padding: 0;
		margin: 0;
		border: 0;
		width: 100%;
		overflow: auto;
		display: block;
	  }
	  /* LineHighlight */
	  .chroma .hl {
		display: block;
		width: 100%;
	  }
	  /* LineNumbersTable */
	  .chroma .lnt {
		margin-right: 0.4em;
		padding: 0 0.4em 0 0.4em;
		display: block;
	  }
	  /* LineNumbers */
	  .chroma .ln {
		margin-right: 0.4em;
		padding: 0 0.4em 0 0.4em;
	  }
	  /* Keyword */
	  .chroma .k {
		color: #00a8c8;
	  }
	  /* KeywordConstant */
	  .chroma .kc {
		color: #00a8c8;
	  }
	  /* KeywordDeclaration */
	  .chroma .kd {
		color: #00a8c8;
	  }
	  /* KeywordNamespace */
	  .chroma .kn {
		color: #f92672;
	  }
	  /* KeywordPseudo */
	  .chroma .kp {
		color: #00a8c8;
	  }
	  /* KeywordReserved */
	  .chroma .kr {
		color: #00a8c8;
	  }
	  /* KeywordType */
	  .chroma .kt {
		color: #00a8c8;
	  }
	  /* Name */
	  .chroma .n {
		color: #111111;
	  }
	  /* NameAttribute */
	  .chroma .na {
		color: #75af00;
	  }
	  /* NameBuiltin */
	  .chroma .nb {
		color: #111111;
	  }
	  /* NameBuiltinPseudo */
	  .chroma .bp {
		color: #111111;
	  }
	  /* NameClass */
	  .chroma .nc {
		color: #75af00;
	  }
	  /* NameConstant */
	  .chroma .no {
		color: #00a8c8;
	  }
	  /* NameDecorator */
	  .chroma .nd {
		color: #75af00;
	  }
	  /* NameEntity */
	  .chroma .ni {
		color: #111111;
	  }
	  /* NameException */
	  .chroma .ne {
		color: #75af00;
	  }
	  /* NameFunction */
	  .chroma .nf {
		color: #75af00;
	  }
	  /* NameFunctionMagic */
	  .chroma .fm {
		color: #111111;
	  }
	  /* NameLabel */
	  .chroma .nl {
		color: #111111;
	  }
	  /* NameNamespace */
	  .chroma .nn {
		color: #111111;
	  }
	  /* NameOther */
	  .chroma .nx {
		color: #75af00;
	  }
	  /* NameProperty */
	  .chroma .py {
		color: #111111;
	  }
	  /* NameTag */
	  .chroma .nt {
		color: #f92672;
	  }
	  /* NameVariable */
	  .chroma .nv {
		color: #111111;
	  }
	  /* NameVariableClass */
	  .chroma .vc {
		color: #111111;
	  }
	  /* NameVariableGlobal */
	  .chroma .vg {
		color: #111111;
	  }
	  /* NameVariableInstance */
	  .chroma .vi {
		color: #111111;
	  }
	  /* NameVariableMagic */
	  .chroma .vm {
		color: #111111;
	  }
	  /* Literal */
	  .chroma .l {
		color: #ae81ff;
	  }
	  /* LiteralDate */
	  .chroma .ld {
		color: #d88200;
	  }
	  /* LiteralString */
	  .chroma .s {
		color: #d88200;
	  }
	  /* LiteralStringAffix */
	  .chroma .sa {
		color: #d88200;
	  }
	  /* LiteralStringBacktick */
	  .chroma .sb {
		color: #d88200;
	  }
	  /* LiteralStringChar */
	  .chroma .sc {
		color: #d88200;
	  }
	  /* LiteralStringDelimiter */
	  .chroma .dl {
		color: #d88200;
	  }
	  /* LiteralStringDoc */
	  .chroma .sd {
		color: #d88200;
	  }
	  /* LiteralStringDouble */
	  .chroma .s2 {
		color: #d88200;
	  }
	  /* LiteralStringEscape */
	  .chroma .se {
		color: #8045ff;
	  }
	  /* LiteralStringHeredoc */
	  .chroma .sh {
		color: #d88200;
	  }
	  /* LiteralStringInterpol */
	  .chroma .si {
		color: #d88200;
	  }
	  /* LiteralStringOther */
	  .chroma .sx {
		color: #d88200;
	  }
	  /* LiteralStringRegex */
	  .chroma .sr {
		color: #d88200;
	  }
	  /* LiteralStringSingle */
	  .chroma .s1 {
		color: #d88200;
	  }
	  /* LiteralStringSymbol */
	  .chroma .ss {
		color: #d88200;
	  }
	  /* LiteralNumber */
	  .chroma .m {
		color: #ae81ff;
	  }
	  /* LiteralNumberBin */
	  .chroma .mb {
		color: #ae81ff;
	  }
	  /* LiteralNumberFloat */
	  .chroma .mf {
		color: #ae81ff;
	  }
	  /* LiteralNumberHex */
	  .chroma .mh {
		color: #ae81ff;
	  }
	  /* LiteralNumberInteger */
	  .chroma .mi {
		color: #ae81ff;
	  }
	  /* LiteralNumberIntegerLong */
	  .chroma .il {
		color: #ae81ff;
	  }
	  /* LiteralNumberOct */
	  .chroma .mo {
		color: #ae81ff;
	  }
	  /* Operator */
	  .chroma .o {
		color: #f92672;
	  }
	  /* OperatorWord */
	  .chroma .ow {
		color: #f92672;
	  }
	  /* Punctuation */
	  .chroma .p {
		color: #111111;
	  }
	  /* Comment */
	  .chroma .c {
		color: #75715e;
	  }
	  /* CommentHashbang */
	  .chroma .ch {
		color: #75715e;
	  }
	  /* CommentMultiline */
	  .chroma .cm {
		color: #75715e;
	  }
	  /* CommentSingle */
	  .chroma .c1 {
		color: #75715e;
	  }
	  /* CommentSpecial */
	  .chroma .cs {
		color: #75715e;
	  }
	  /* CommentPreproc */
	  .chroma .cp {
		color: #75715e;
	  }
	  /* CommentPreprocFile */
	  .chroma .cpf {
		color: #75715e;
	  }
	  /* GenericEmph */
	  .chroma .ge {
		font-style: italic;
	  }
	  /* GenericStrong */
	  .chroma .gs {
		font-weight: bold;
	  }
`
)

var (
	htmlWrap = `
<html>
	<meta>
	<style>
{{ css }}
	</style>
	</meta>

<body>
{{ htmlBody }}
</body>

</html>
`
)

var (
	fullHTMLWrap string
)

func getFullHTMLWrap() string {
	if len(fullHTMLWrap) == 0 {
		fullHTMLWrap = strings.Replace(htmlWrap, "{{ css }}", css, -1)
		if fullHTMLWrap == htmlWrap {
			panic("failed to replace {{ css }} in htmlWrap")
		}
	}
	return fullHTMLWrap
}

// wrap HTML body in more HTML to create a full, stand-alone HTML page
func makeFullHTML(htmlBody []byte) []byte {
	wrap := getFullHTMLWrap()
	html := strings.Replace(wrap, "{{ htmlBody }}", string(htmlBody), -1)
	if len(htmlBody) > 0 && wrap == html {
		panic("failed to replace {{ htmlBody }} in fullHTMLWrap")
	}
	return []byte(html)
}
